site_name: Vsign
nav:
    - Home: README.md
    - Projeto:
        - 'Termo de Abertura de Projeto': 'project/tap.md'
        - 'Identidade Visual': 'project/identidadeVisual.md'
        - 'Plano de Negócios': 'project/canvas.md'
        - 'Plano de Comunicação Interna': 'project/planoComunicacao.md'
        - 'Roadmap': 'project/roadmap.md'
        - 'EAP': 'project/eap.md'
        - 'Documento de Visão': 'project/vision-document.md'
        - 'Documento de Arquitetura': 'project/architectureDocument.md'
        - 'Diagrama de casos de uso': 'project/useCasesDiagram.md'
        - 'Análise Crítica de artigo': 'project/articleCriticalAnalysis.md'
    - Gerenciamento de Projeto:
        - 'Plano de Gerenciamento de Configuração de Software': 'managementProject/gcs.md'
        - 'Folha de Estilo': 'managementProject/styleGuide.md'
    - Sprints:
        - 'Pré-Sprint': 'sprints/preSprint.md'
        - 'Sprint 1': 'sprints/sprint1.md'
        - 'Sprint 2': 'sprints/sprint2.md'
        - 'Sprint 3': 'sprints/sprint3.md'
        - 'Sprint 4': 'sprints/sprint4.md'
        - 'Sprint 5': 'sprints/sprint5.md'
        - 'Sprint 6': 'sprints/sprint6.md'
    - Atas de Reunião:
        - '29/08/2019': 'meetings/reuniao29_08_19.md'
        - '31/08/2019': 'meetings/reuniao31_08_19.md'
        - '05/09/2019': 'meetings/reuniao05_09_19.md'
        - '07/09/2019': 'meetings/reuniao07_09_19.md'
        - '14/09/2019': 'meetings/reuniao14_09_19.md'
        - '21/09/2019': 'meetings/reuniao21_09_19.md'
        - '29/09/2019': 'meetings/reuniao29_09_19.md'
        - '06/10/2019': 'meetings/reuniao06_10_19.md'
        - '12/10/2019': 'meetings/reuniao12_10_19.md'
        - '19/10/2019': 'meetings/reuniao19_10_19.md'
        - '22/10/2019': 'meetings/reuniao22_10_19.md'
        - '26/10/2019': 'meetings/reuniao26_10_19.md'
        - '04/11/2019': 'meetings/reuniao04_11_19.md'
theme: readthedocs
