version: "3"

services:
  db:
    image: postgres
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
    restart: always
    env_file:
      - db.env

  backend:
    build: .
    command: bash -c "bundle check || bundle install && rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - .:/vsign
    ports:
      - "3000:3000"
    depends_on:
      - db
    env_file:
      - ./app.env
