version: 2

references:
  default_docker_ruby_executor: &default_docker_ruby_executor
    image: circleci/ruby:2.6.3-stretch-node
    environment:
      BUNDLE_JOBS: 3
      BUNDLE_RETRY: 3
      BUNDLE_PATH: vendor/bundle
      PGHOST: 127.0.0.1
      PGUSER: vsign
      PGPASSWORD: ""
      RAILS_ENV: test
  postgres: &postgres
    image: circleci/postgres:9.5-alpine
    environment:
      POSTGRES_USER: vsign
      POSTGRES_DB: postgres
      POSTGRES_PASSWORD: ""

jobs:
  build:
    docker:
      - *default_docker_ruby_executor
    steps:
      - checkout
      # Which version of bundler?
      - run:
          name: Which bundler?
          command: bundle -v
      # bundle cache
      - restore_cache:
          keys:
            - vsign-{{ checksum "backend/Gemfile.lock" }}
            - vsign-
      - run:
          working_directory: ./backend
          name: Bundle Install
          command: bundle check || bundle install
      # Store bundle cache
      - save_cache:
          key: vsign-{{ checksum "backend/Gemfile.lock" }}
          paths:
            - vendor/bundle
      # Only necessary if app uses webpacker or yarn in some other way
      # - restore_cache:
      #     keys:
      #       - rails-demo-yarn-{{ checksum "yarn.lock" }}
      #       - rails-demo-yarn-
      # - run:
      #     name: Yarn Install
      #     command: yarn install --cache-folder ~/.cache/yarn
      # # Store yarn / webpacker cache
      # - save_cache:
      #     key: rails-demo-yarn-{{ checksum "yarn.lock" }}
      #     paths:
      #       - ~/.cache/yarn
    deploy_staging:
      docker:
        - image: buildpack-deps:trusty
      steps:
        - checkout
        - run:
            name: Deploy Backend to Heroku
            command: |
              git push https://heroku:$HEROKU_API_KEY@git.heroku.com/vsign-api-staging.git `git subtree split --prefix backend develop`:develop --force
    deploy_production:
      docker:
        - image: buildpack-deps:trusty
      steps:
        - checkout
        - run:
            name: Deploy Backend to Heroku
            command: |
              git push https://heroku:$HEROKU_API_KEY@git.heroku.com/vsign-api.git `git subtree split --prefix backend master`:master --force
  test:
    #parallelism: 3
    docker:
      - *default_docker_ruby_executor
      - *postgres
    steps:
      - checkout
      - restore_cache:
          keys:
            - vsign-{{ checksum "backend/Gemfile.lock" }}
            - vsign-
      - run:
          working_directory: ./backend
          name: Bundle Install
          command: bundle check || bundle install
      # - restore_cache:
      #     keys:
      #       - rails-demo-yarn-{{ checksum "yarn.lock" }}
      #       - rails-demo-yarn-#
      - run:
          working_directory: ./backend
          name: Wait for DB
          command: dockerize -wait tcp://localhost:5432 -timeout 1m
           #WAITING schema and tests in vsign projet
      # - run:                                   
      #     working_directory: ./backend
      #     name: Database setup
      #     command: bundle exec rails db:schema:load --trace
      # Run rspec in parallel
      # - run:
      #     working_directory: ./backend
      #     command: |
      #       mkdir /tmp/test-results
      #       TESTFILES=$(circleci tests glob "spec/**/*_spec.rb" | circleci tests split --split-by=timings)
      #       bundle exec rspec $TESTFILES --profile 10 --format RspecJunitFormatter --out /tmp/test-results/rspec.xml --format progress
      # - store_test_results:
      #     path: /tmp/test-results
      # - store_artifacts:
      #     path: /tmp/test-results
      #     destination: test-results

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - test:
          requires:
            - build
  build_and_deploy_production:
    jobs:
      - build
      - deploy_production:
          requires:
            - build
          filters:
            branches:
              only: master
  build_and_deploy_staging:
    jobs:
      - build
      - deploy_staging:
          requires:
            - build
          filters:
            branches:
              only: us19/#81_auto_deploy